change set-output to the new system
OctoPrint/actions pull request #1
Opened 2023-01-30 20:32 UTC by max246

Update the system to set output using the new convention from github

This is releated to ticket #6

2023-02-02 14:50 UTC, foosel requested changes

2023-02-02 14:50 UTC, foosel commented on package.json
> +{
Please get rid of this, we don't need that, and if we do, I'd like to know why and see the links replaced ;)

2023-02-02 15:20 UTC, max246 commented on package.json
> +{
I suppose the other one as well from package-lock?

2023-02-02 15:37 UTC, foosel commented on package.json
> +{
Yes, indeed 👍

2023-02-02 15:38 UTC, foosel commented on package.json
> +{
and also the (accidental) rename of `issue-validation/package-locks.json` to `issue-validation/package-locka.json`

2023-02-08 14:20 UTC, foosel approved these changes

2023-02-08 14:20 UTC, merged